---
abstract: 'Catalyst based application'
author:
  - 'Chisel Wright,,,'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Cleavages
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller::Validation::DFV: 0
  Catalyst::Controller::reCAPTCHA: 0
  Catalyst::Log::Log4perl: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Model::File: 0
  Catalyst::Plugin::Authentication: 0.100091
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::FillInForm: 0
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::Images: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Upload::Digest: 0.02
  Catalyst::Plugin::Upload::Image::Magick: 0
  Catalyst::Plugin::Upload::MIME: 0.01
  Catalyst::Runtime: 5.7015
  Catalyst::View::TT: 0
  Config::General: 0
  DBIx::Class: 0
  Data::FormValidator::Constraints: 0
  Digest::MD5: 0
  Path::Class: 0
  Perl6::Export::Attrs: 0
  Template::Plugin::Gravatar: 0
  parent: 0
  version: 0
version: 0.0.9
